name = "glebs"
target = "javascript"
version = "1.0.0"

description = "An OAuth PKCE helper for Gleam in Browser. You can easily use this with lustre."
licences = ["Apache-2.0"]
repository = { type = "github", user = "andho", repo = "glebs" }

gleam = ">= 1.9.1 and < 2.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_fetch = ">= 1.1.0 and < 2.0.0"
sketch = ">= 4.0.0 and < 5.0.0"
lustre = ">= 4.6.4 and < 5.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.4 and < 2.0.0"
pprint = ">= 1.0.4 and < 2.0.0"
