name = "glebs"
target = "javascript"
version = "0.1.1"

description = "An OAuth PKCE helper for Gleam in Browser. You can easily use this with lustre."
licences = ["Apache-2.0"]
repository = { type = "github", user = "andho", repo = "glebs" }

gleam = ">= 1.5.1 and < 2.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
gleam_fetch = ">= 1.1.0 and < 2.0.0"
decode = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.4 and < 2.0.0"
pprint = ">= 1.0.4 and < 2.0.0"
